/**
 * Signal Service
 *
 * Creates and lists trade signals generated by strategies.
 * Signals are the precursor to trade proposals.
 */

const db = require('../../config/database');
const audit = require('./auditService');

async function createSignal({ strategyId, symbol, direction, signalData, featureSnapshot }) {
  const result = await db.query(
    `INSERT INTO trade_signals (strategy_id, symbol, direction, signal_data, feature_snapshot, status)
     VALUES ($1, $2, $3, $4, $5, 'SIGNAL_DETECTED')
     RETURNING *`,
    [strategyId, symbol.toUpperCase(), direction, JSON.stringify(signalData || {}), JSON.stringify(featureSnapshot || {})]
  );

  const signal = result.rows[0];
  await audit.recordEvent('signal_detected', 'trade_signal', signal.id, {
    symbol: signal.symbol, direction: signal.direction, strategy_id: strategyId
  });

  return signal;
}

async function getById(id) {
  const result = await db.query(
    `SELECT * FROM trade_signals WHERE id = $1`,
    [id]
  );
  return result.rows[0] || null;
}

async function listSignals({ strategyId, symbol, status, limit = 50 } = {}) {
  const params = [];
  const conditions = [];

  if (strategyId) {
    params.push(strategyId);
    conditions.push(`strategy_id = $${params.length}`);
  }
  if (symbol) {
    params.push(symbol.toUpperCase());
    conditions.push(`symbol = $${params.length}`);
  }
  if (status) {
    params.push(status);
    conditions.push(`status = $${params.length}`);
  }

  const where = conditions.length ? 'WHERE ' + conditions.join(' AND ') : '';
  params.push(limit);

  const result = await db.query(
    `SELECT * FROM trade_signals
     ${where}
     ORDER BY detected_at DESC
     LIMIT $${params.length}`,
    params
  );
  return result.rows;
}

async function updateStatus(signalId, newStatus) {
  const result = await db.query(
    `UPDATE trade_signals
     SET status = $2
     WHERE id = $1
     RETURNING *`,
    [signalId, newStatus]
  );

  const signal = result.rows[0];
  if (signal) {
    await audit.recordEvent('signal_status_changed', 'trade_signal', signalId, {
      status: newStatus
    });
  }

  return signal;
}

module.exports = {
  createSignal,
  getById,
  listSignals,
  updateStatus
};